POST http://localhost:8080/produto
Content-Type: application/json

{
  "id" : 1,
  "nome" : "Produto1",
  "descricao" : "Produto 2",
  "fotoUrl" : "Foto do Produto 1",
  "dataCadastro" : "2021-01-19 03:14:07",
  "dataUltimaAtualizacao" : "2021-23-19 15:00:00",
  "valorUnitario" : 11.00
}

###

GET http://localhost:8080/produto/1
Accept: application/json

###

GET http://localhost:8080/produto?nome=Produto1
Accept: application/json

###

GET http://localhost:8080/produto?valorMinimo=9&valorMaximo=12
Accept: application/json

###

GET http://localhost:8080/produto?nome=Produto1&valorMinimo=9&valorMaximo=12
Accept: application/json

###